import { Collection, CompletedManga, Stats } from "./types";

export const completedSeries: CompletedManga[] = [
  {
    id: "1",
    rank: 1,
    title: "Solo Leveling",
    slug: "solo-leveling",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Fantasy"],
    rating: 4.9,
    readers: "2.6M",
    chapters: 179,
    completed: true,
    verified: true,
  },
  {
    id: "2",
    rank: 2,
    title: "The Beginning After The End",
    slug: "tbate",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Fantasy", "Adventure", "Drama"],
    rating: 4.8,
    readers: "2.3M",
    chapters: 198,
    completed: true,
    verified: true,
  },
  {
    id: "3",
    rank: 3,
    title: "Omniscient Reader's Viewpoint",
    slug: "orv",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Fantasy", "Sci-Fi"],
    rating: 4.8,
    readers: "2.1M",
    chapters: 222,
    completed: true,
    verified: true,
  },
  {
    id: "4",
    rank: 4,
    title: "The Boxer",
    slug: "the-boxer",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Sports", "Action", "Drama"],
    rating: 4.7,
    readers: "1.6M",
    chapters: 139,
    completed: true,
  },
  {
    id: "5",
    rank: 5,
    title: "Legend of the Northern Blade",
    slug: "lotnb",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Adventure"],
    rating: 4.7,
    readers: "1.5M",
    chapters: 120,
    completed: true,
  },
  {
    id: "6",
    rank: 6,
    title: "Tower of God",
    slug: "tower-of-god",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Fantasy", "Adventure"],
    rating: 4.6,
    readers: "1.4M",
    chapters: 537,
    completed: true,
  },
  {
    id: "7",
    rank: 7,
    title: "Noblesse",
    slug: "noblesse",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "School"],
    rating: 4.6,
    readers: "987K",
    chapters: 544,
    completed: true,
  },
  {
    id: "8",
    rank: 8,
    title: "I Became the Male Lead's Adopted Daughter",
    slug: "adopted-daughter",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Romance", "Fantasy", "Drama"],
    rating: 4.6,
    readers: "872K",
    chapters: 89,
    completed: true,
  },
];

export const collections: Collection[] = [
  {
    id: "1",
    title: "Completed Fantasy",
    image: "/banners/the-beginning-after-the-end.jpeg",
    series: 452,
  },
  {
    id: "2",
    title: "Completed Romance",
    image: "/banners/the-beginning-after-the-end.jpeg",
    series: 318,
  },
  {
    id: "3",
    title: "Completed Action",
    image: "/banners/the-beginning-after-the-end.jpeg",
    series: 624,
  },
  {
    id: "4",
    title: "Completed School",
    image: "/banners/the-beginning-after-the-end.jpeg",
    series: 186,
  },
  {
    id: "5",
    title: "Completed Drama",
    image: "/banners/the-beginning-after-the-end.jpeg",
    series: 275,
  },
];

export const stats: Stats = {
  totalSeries: 1286,
  averageChapters: 164,
  highestRated: "Solo Leveling",
  longestSeries: "Tower of God",
};
