import { Genre, TrendingGenre, GenreSeries } from "./types";

export const genres: Genre[] = [
  {
    id: 1,
    name: "Action",
    slug: "action",
    icon: "⚔️",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 2350,
    color: "var(--genre-action)",
  },
  {
    id: 2,
    name: "Fantasy",
    slug: "fantasy",
    icon: "✨",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 1890,
    color: "var(--genre-fantasy)",
  },
  {
    id: 3,
    name: "Romance",
    slug: "romance",
    icon: "💜",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 1560,
    color: "var(--genre-romance)",
  },
  {
    id: 4,
    name: "Adventure",
    slug: "adventure",
    icon: "🧭",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 1320,
    color: "var(--genre-adventure)",
  },
  {
    id: 5,
    name: "Comedy",
    slug: "comedy",
    icon: "😂",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 980,
    color: "var(--genre-comedy)",
  },
  {
    id: 6,
    name: "School",
    slug: "school",
    icon: "🎓",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    seriesCount: 870,
    color: "var(--genre-school)",
  },
];

export const trendingGenres: TrendingGenre[] = [
  {
    rank: 1,
    name: "Action",
    percentage: 85,
    icon: "⚔️",
  },
  {
    rank: 2,
    name: "Fantasy",
    percentage: 76,
    icon: "✨",
  },
  {
    rank: 3,
    name: "Reincarnation",
    percentage: 64,
    icon: "♻️",
  },
  {
    rank: 4,
    name: "Murim",
    percentage: 62,
    icon: "🥋",
  },
  {
    rank: 5,
    name: "Adventure",
    percentage: 58,
    icon: "🧭",
  },
];

export const popularGenreSeries: GenreSeries[] = [
  {
    id: "1",
    title: "Solo Leveling",
    slug: "solo-leveling",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Fantasy"],
    rating: 4.9,
    chapter: 179,
  },
  {
    id: "2",
    title: "Nano Machine",
    slug: "nano-machine",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Sci-Fi"],
    rating: 4.8,
    chapter: 151,
  },
  {
    id: "3",
    title: "The Beginning After The End",
    slug: "tbate",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Fantasy"],
    rating: 4.7,
    chapter: 198,
  },
  {
    id: "4",
    title: "Omniscient Reader",
    slug: "omniscient-reader",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Fantasy", "Drama"],
    rating: 4.7,
    chapter: 204,
  },
  {
    id: "5",
    title: "Swordmaster's Youngest Son",
    slug: "swordmaster",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    genres: ["Action", "Fantasy"],
    rating: 4.6,
    chapter: 97,
  },
];

export const tags = [
  "System",
  "Overpowered",
  "Isekai",
  "Revenge",
  "Time Travel",
  "Magic",
  "Martial Arts",
  "Demon",
  "School",
  "Supernatural",
  "Game",
  "Harem",
  "Villain",
  "Survival",
  "Seinen",
  "Shounen",
  "Psychological",
  "Mecha",
  "Slice of Life",
  "Historical",
  "Sports",
  "Horror",
  "Thriller",
  "Mystery",
];
