import { BookmarkManga } from "./types";

export const bookmarks: BookmarkManga[] = [
  {
    id: "1",
    rank: 1,
    title: "Solo Necromancer",
    slug: "solo-necromancer",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 182,
    rating: 4.9,
    readers: "2.6M",
    genres: ["Action", "Fantasy", "Adventure"],
    progress: 85,
    verified: true,
    status: "Reading",
  },

  {
    id: "2",
    rank: 2,
    title: "The Beginning After The End",
    slug: "the-beginning-after-the-end",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 156,
    rating: 4.8,
    readers: "2.3M",
    genres: ["Fantasy", "Adventure", "Magic"],
    progress: 71,
    verified: true,
    status: "Reading",
  },

  {
    id: "3",
    rank: 3,
    title: "Omniscient Reader's Viewpoint",
    slug: "omniscient-readers-viewpoint",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 220,
    rating: 4.8,
    readers: "2.1M",
    genres: ["Action", "Fantasy", "Sci-Fi"],
    progress: 60,
    verified: true,
    status: "Reading",
  },

  {
    id: "4",
    rank: 4,
    title: "I Became the Male Lead's Adopted Daughter",
    slug: "male-leads-adopted-daughter",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 89,
    rating: 4.7,
    readers: "1.8M",
    genres: ["Romance", "Fantasy", "Drama"],
    progress: 92,
    verified: true,
    status: "Reading",
  },

  {
    id: "5",
    rank: 5,
    title: "A Returner's Magic Should Be Special",
    slug: "a-returners-magic-should-be-special",
    cover: "/bookmarks/returners-magic.jpg",
    chapter: 133,
    rating: 4.7,
    readers: "1.6M",
    genres: ["Action", "Fantasy", "Magic"],
    progress: 33,
    verified: true,
    status: "Reading",
  },

  {
    id: "6",
    rank: 6,
    title: "The Heavenly Demon Destroys the Lich King's Murim",
    slug: "heavenly-demon-lich-king",
    cover: "/bookmarks/heavenly-demon.jpg",
    chapter: 78,
    rating: 4.6,
    readers: "1.4M",
    genres: ["Action", "Fantasy", "Martial Arts"],
    progress: 46,
    verified: true,
    status: "Reading",
  },

  {
    id: "7",
    rank: 7,
    title: "Leveling With The Gods",
    slug: "leveling-with-the-gods",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 64,
    rating: 4.6,
    readers: "1.3M",
    genres: ["Action", "Fantasy"],
    progress: 20,
    verified: true,
    status: "Plan To Read",
  },

  {
    id: "8",
    rank: 8,
    title: "The Villainess Turns the Hourglass",
    slug: "villainess-turns-the-hourglass",
    cover: "/banners/the-beginning-after-the-end.jpeg",
    chapter: 125,
    rating: 4.6,
    readers: "987K",
    genres: ["Romance", "Fantasy"],
    progress: 100,
    verified: true,
    status: "Completed",
  },
];
