import { UpdateItem } from "./types";

export const today: UpdateItem[] = [
  {
    id: "1",
    title: "Solo Necromancer",
    slug: "solo-necromancer",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 182,
    genres: ["Action", "Fantasy", "Adventure"],
    updatedAt: "Just now",
    isNew: true,
  },
  {
    id: "2",
    title: "The Beginning After The End",
    slug: "the-beginning-after-the-end",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 215,
    genres: ["Fantasy", "Adventure", "Magic"],
    updatedAt: "8 minutes ago",
    isNew: true,
  },
  {
    id: "3",
    title: "Solo Max-Level Newbie",
    slug: "solo-max-level-newbie",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 198,
    genres: ["Action", "Fantasy", "Game"],
    updatedAt: "26 minutes ago",
    isNew: true,
  },
  {
    id: "4",
    title: "Return of the Disaster-Class Hero",
    slug: "return-of-the-disaster-class-hero",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 127,
    genres: ["Action", "Fantasy"],
    updatedAt: "1 hour ago",
  },
];

export const yesterday: UpdateItem[] = [
  {
    id: "5",
    title: "Omniscient Reader's Viewpoint",
    slug: "omniscient-readers-viewpoint",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 264,
    genres: ["Action", "Fantasy", "Drama"],
    updatedAt: "Yesterday • 10:45 PM",
  },
  {
    id: "6",
    title: "The World After The Fall",
    slug: "the-world-after-the-fall",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 176,
    genres: ["Fantasy", "Action"],
    updatedAt: "Yesterday • 8:10 PM",
  },
  {
    id: "7",
    title: "SSS-Class Suicide Hunter",
    slug: "sss-class-suicide-hunter",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 146,
    genres: ["Fantasy", "Adventure"],
    updatedAt: "Yesterday • 6:30 PM",
  },
  {
    id: "8",
    title: "Tower of God",
    slug: "tower-of-god",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 675,
    genres: ["Action", "Adventure", "Fantasy"],
    updatedAt: "Yesterday • 4:05 PM",
  },
];

export const june20: UpdateItem[] = [
  {
    id: "9",
    title: "Eleceed",
    slug: "eleceed",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 357,
    genres: ["Action", "Comedy", "School"],
    updatedAt: "June 20 • 9:30 PM",
  },
  {
    id: "10",
    title: "Nano Machine",
    slug: "nano-machine",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 276,
    genres: ["Action", "Martial Arts"],
    updatedAt: "June 20 • 6:45 PM",
  },
  {
    id: "11",
    title: "Murim Login",
    slug: "murim-login",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 223,
    genres: ["Action", "Comedy", "Martial Arts"],
    updatedAt: "June 20 • 3:10 PM",
  },
  {
    id: "12",
    title: "Pick Me Up, Infinite Gacha",
    slug: "pick-me-up-infinite-gacha",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 151,
    genres: ["Fantasy", "Action", "Game"],
    updatedAt: "June 20 • 12:15 PM",
  },
  {
    id: "13",
    title: "Academy's Genius Swordsman",
    slug: "academys-genius-swordsman",
    cover: "/banners/solo-max-level-newbie.png",
    chapter: 84,
    genres: ["Fantasy", "School"],
    updatedAt: "June 20 • 10:00 AM",
  },
];
